'use client';
import {useMemo,useState} from 'react'; import Link from 'next/link'; import {Search24Regular, Cart24Regular, Add24Regular} from '@fluentui/react-icons';
const items=[
{id:'BT-001',name:'Sorted bottle tops',category:'Plastics',unit:'kg',price:180,location:'Nairobi',condition:'Clean / sorted',buyer:'Artists'},
{id:'BR-010',name:'Reusable construction bricks',category:'Construction',unit:'piece',price:25,location:'Kiambu',condition:'Used / intact',buyer:'Builders'},
{id:'PA-204',name:'Clean paper feedstock',category:'Paper',unit:'kg',price:70,location:'Nairobi',condition:'Dry / sorted',buyer:'Paper makers'},
{id:'TX-017',name:'Tailoring textile offcuts',category:'Textiles',unit:'kg',price:120,location:'Nairobi',condition:'Mixed sizes',buyer:'Makers'},
{id:'EL-031',name:'Laptop parts lot',category:'Electronics',unit:'lot',price:2500,location:'Nairobi',condition:'For repair / parts',buyer:'Repairers'},
{id:'MC-044',name:'Machine components',category:'Machines',unit:'lot',price:1400,location:'Athi River',condition:'Mixed / inspected',buyer:'Fabricators'}];
export default function Marketplace(){const [q,setQ]=useState('');const [cat,setCat]=useState('All');const [cart,setCart]=useState<string[]>([]);const shown=useMemo(()=>items.filter(x=>(cat==='All'||x.category===cat)&&(`${x.name} ${x.category} ${x.location}`.toLowerCase().includes(q.toLowerCase()))),[q,cat]);return <main className="section wash"><div className="container"><div className="sectionHead"><div><div className="eyebrow">MATERIAL MARKETPLACE</div><h2>Find something with a second life.</h2></div><Link className="btn primary" href="/checkout"><Cart24Regular/> Cart ({cart.length})</Link></div><div className="marketGrid"><aside className="panel filters"><b>Search & filter</b><label>Search</label><div style={{display:'flex',gap:6}}><Search24Regular style={{marginTop:10}}/><input className="field" value={q} onChange={e=>setQ(e.target.value)} placeholder="Bottle tops, laptop parts..."/></div><label>Category</label><select className="field" value={cat} onChange={e=>setCat(e.target.value)}><option>All</option>{[...new Set(items.map(x=>x.category))].map(c=><option key={c}>{c}</option>)}</select><div className="notice" style={{marginTop:18}}>Buyers can request pickup or select an available collection point during checkout.</div></aside><section className="materials">{shown.map(x=><article className="material" key={x.id}><div className="materialTop"><div className="iconBox"><RecycleGlyph/></div></div><div className="materialBody"><span className="tag">{x.category}</span><h3>{x.name}</h3><p>{x.condition} · {x.location} · Buyer use: {x.buyer}</p><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span className="price">KES {x.price.toLocaleString()}/{x.unit}</span><button className="btn" onClick={()=>setCart(v=>v.includes(x.id)?v:[...v,x.id])}><Add24Regular/> Add</button></div></div></article>)}</section></div></div></main>}
function RecycleGlyph(){return <span style={{fontWeight:700,fontSize:18}}>R</span>}
